// "use client";





import Layout from "@/components/Layoutfile/Layoutfile";

export const metadata = {
  title: "MindScribe",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
 
      // <div className="App">
      // <div className="AppGlass">
     
        <Layout>
        <div>{children}</div> 
        </Layout>
    //   </div>
    // </div>
   
  );
}


